name: Validate React starter
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v7.1.0
        with:
          node-version: '24'
          cache: npm
      - run: npm ci
      - run: npm run format:check
      - run: npm run build
      - run: npx playwright install --with-deps chromium
      - run: npm run test:e2e
